### ISSUE TITLE
安装Bee失败

### ISSUE THREAD

**Issue by yangfan21** [beego/bee#582]
go: github.com/derekparker/delve@v1.2.0: parsing go.mod: unexpected module path "github.com/go-delve/delve"

go env 

GOARCH="amd64"
GOBIN="/Users/yangfan/opt/go/bin"
GOCACHE="/Users/yangfan/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/yangfan/Documents/Code/GoProject"
GOPROXY=""
GORACE=""
GOROOT="/Users/yangfan/opt/go"
GOTMPDIR=""
GOTOOLDIR="/Users/yangfan/opt/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kz/430wrhm112qbp2gps5lm228w0000gn/T/go-build160664175=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by hantmac** [comment]
- 参考这个[issue](https://github.com/beego/bee/issues/574)
- 另外，之前也提过一个[意见](https://github.com/beego/bee/issues/575)看来一直没有处理，导致现在还是报同样的错误。

**Comment by yangfan21** [comment]
我看见是go.mod 里面引用了github.com/derekparker/delve v0.12.1 但是dlv 迁移到了github.com/go-delve/delve ，这个应该合入吧，否则我一直都go get 不会成功

**Comment by yangfan21** [comment]
问题是我现在希望能够使用bee 自己clone 然后build吗？

**Comment by eyasliu** [comment]
GO111MODULE=off go get -u github.com/beego/bee

先把go mod给关闭了，再安装就可以了

**Comment by realguan** [comment]
我解决了，看这个教程  www.678fly.cn

**Comment by eyasliu** [comment]
@realguan 如果你想在beego使用 go module，请注意[这个 issue ](https://github.com/astaxie/beego/issues/3450)

**Comment by imac-beep** [comment]
> GO111MODULE=off go get -u github.com/beego/bee
> 
> 先把go mod给关闭了，再安装就可以了

使用GoProxy.cn的话，是要求GO111MODULE=on的

**Comment by yeszao** [comment]
有个补丁可以用，先执行：
```bash
go get github.com/gadelkareem/bee@fix-mod
```
补丁位置：https://github.com/beego/bee/pull/653

**Comment by hyhy01** [comment]
> 有个补丁可以用，先执行：
> 
> ```shell
> go get github.com/gadelkareem/bee@fix-mod
> ```
> 
> 补丁位置：#653

我执行了结果一样

**Comment by kurosakisora** [comment]
vim go.mod, add this fixed.

replace github.com/derekparker/delve => github.com/go-delve/delve v1.4.0 // indirect

**Comment by senjyure** [comment]
C:\Users\mi>go get github.com/beego/bee
package golang.org/x/text/transform: unrecognized import path "golang.org/x/text/transform" (https fetch: Get https://golang.org/x/text/transform?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
package golang.org/x/text/unicode/norm: unrecognized import path "golang.org/x/text/unicode/norm" (https fetch: Get https://golang.org/x/text/unicode/norm?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
请问这个是怎么回事

**Comment by flycash** [comment]
> C:\Users\mi>go get github.com/beego/bee
> package golang.org/x/text/transform: unrecognized import path "golang.org/x/text/transform" (https fetch: Get https://golang.org/x/text/transform?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
> package golang.org/x/text/unicode/norm: unrecognized import path "golang.org/x/text/unicode/norm" (https fetch: Get https://golang.org/x/text/unicode/norm?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
> 请问这个是怎么回事

连接不上golang.org，考虑翻墙或者使用代理。
